apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: coldfront
  namespace: coldfront
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: coldfront
    weight: 100
  wildcardPolicy: None
