apiVersion: batch/v1
kind: CronJob
metadata:
  name: invoice-cronjob
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: invoice-cronjob
            image: ghcr.io/nerc-project/coldfront-nerc:v0.4.2
            env:
              - name: DATABASE_HOST
                valueFrom:
                  secretKeyRef:
                    name: coldfront-postgres-ha-pguser-coldfront-postgres-ha
                    key: host
              - name: DATABASE_PORT
                valueFrom:
                  secretKeyRef:
                    name: coldfront-postgres-ha-pguser-coldfront-postgres-ha
                    key: port
              - name: DATABASE_NAME
                valueFrom:
                  secretKeyRef:
                    name: coldfront-postgres-ha-pguser-coldfront-postgres-ha
                    key: dbname
              - name: DATABASE_USER
                valueFrom:
                  secretKeyRef:
                    name: coldfront-postgres-ha-pguser-coldfront-postgres-ha
                    key: user
              - name: DATABASE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: coldfront-postgres-ha-pguser-coldfront-postgres-ha
                    key: password
            envFrom:
            - secretRef:
                name: storage-invoice-s3-secrets
