apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: storage-invoice-s3-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: storage-invoice-s3-secrets
  data:
  - secretKey: S3_INVOICING_ACCESS_KEY_ID
    remoteRef:
      key: coldfront/storage-invoice-s3
      property: S3_INVOICING_ACCESS_KEY_ID
  - secretKey: S3_INVOICING_SECRET_ACCESS_KEY
    remoteRef:
      key: coldfront/storage-invoice-s3
      property: S3_INVOICING_SECRET_ACCESS_KEY
