apiVersion: apps/v1
kind: Deployment
metadata:
  name: coldfront-qcluster-deployment
spec:
  template:
    spec:
      containers:
      - name: coldfront-qcluster
        image: ghcr.io/nerc-project/coldfront-nerc:v0.4.2
        env:
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: coldfront-postgres-ha-pguser-coldfront-postgres-ha
                key: host
          - name: DATABASE_PORT
            valueFrom:
              secretKeyRef:
                name: coldfront-postgres-ha-pguser-coldfront-postgres-ha
                key: port
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: coldfront-postgres-ha-pguser-coldfront-postgres-ha
                key: dbname
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: coldfront-postgres-ha-pguser-coldfront-postgres-ha
                key: user
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: coldfront-postgres-ha-pguser-coldfront-postgres-ha
                key: password
        envFrom:
        - configMapRef:
            name: coldfront-configmap
        - secretRef:
            name: coldfront-secrets
