apiVersion: v1
kind: Service
metadata:
  name: coldfront-static-files
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: coldfront-app
    coldfront-deployment: coldfront-static-files
