apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: coldfront
spec:
  host: 'coldfront-nerc.testing'
  port:
    targetPort: http
  to:
    kind: Service
    name: coldfront
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
