apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: coldfront-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: coldfront-secrets
  data:
  - secretKey: OIDC_RP_CLIENT_ID
    remoteRef:
      key: coldfront/oidc
      property: OIDC_RP_CLIENT_ID
  - secretKey: OIDC_RP_CLIENT_SECRET
    remoteRef:
      key: coldfront/oidc
      property: OIDC_RP_CLIENT_SECRET
  - secretKey: OPENSTACK_NERC_APPLICATION_CREDENTIAL_ID
    remoteRef:
      key: coldfront/nerc-openstack-app-creds
      property: OPENSTACK_NERC_APPLICATION_CREDENTIAL_ID
  - secretKey: OPENSTACK_NERC_APPLICATION_CREDENTIAL_SECRET
    remoteRef:
      key: coldfront/nerc-openstack-app-creds
      property: OPENSTACK_NERC_APPLICATION_CREDENTIAL_SECRET
  - secretKey: OPENSHIFT_NERC_OCP_USERNAME
    remoteRef:
      key: coldfront/nerc-openshift-acct-mgt-credentials
      property: OPENSHIFT_NERC_USERNAME
  - secretKey: OPENSHIFT_NERC_OCP_PASSWORD
    remoteRef:
      key: coldfront/nerc-openshift-acct-mgt-credentials
      property: OPENSHIFT_NERC_PASSWORD
  - secretKey: KEYCLOAK_USER
    remoteRef:
      key: coldfront/keycloak-creds
      property: KEYCLOAK_USER
  - secretKey: KEYCLOAK_PASS
    remoteRef:
      key: coldfront/keycloak-creds
      property: KEYCLOAK_PASS
  - secretKey: SECRET_KEY
    remoteRef:
      key: coldfront/django
      property: SECRET_KEY
  - secretKey: EMAIL_HOST_USER
    remoteRef:
      key: accounts/aws/mghpcc/smtp
      property: EMAIL_HOST_USER
  - secretKey: EMAIL_HOST_PASSWORD
    remoteRef:
      key: accounts/aws/mghpcc/smtp
      property: EMAIL_HOST_PASSWORD
