apiVersion: v1
kind: ConfigMap
metadata:
  name: coldfront-configmap
data:
  DEBUG: "True"
  DB_HOST: "coldfront-database-mariadb.argocd"
  DB_URL: "mysql://coldfront:nomoresecret@coldfront-database-mariadb.argocd:3306/coldfront"
  OPENSTACK_DEVSTACK_APPLICATION_CREDENTIAL_ID: ""
  OPENSTACK_DEVSTACK_APPLICATION_CREDENTIAL_SECRET: ""
